name = "DSSE_SEND"
uuid = "f0f1bc1f-8013-4726-89d9-13db6752d42d"
authors = ["MartaVanin <marta.vanin@esat.kuleuven.be> and contributors"]
version = "0.1.0"

[deps]
PowerModelsAnalytics = "7425d11c-6b70-11e9-2bc6-9bcd3191d4b9"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
PowerModelsDistributionStateEstimation = "d0713e65-ce0c-4a8e-a1da-2ed737d217c5"

[compat]
PowerModelsDistribution = "0.14"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
